### ISSUE TITLE
REPL Support for Typescript

### ISSUE THREAD

**Issue by Tus1688** [michaelb/sniprun#115]
**Describe the language you want support for (compiler, specificities)**
I'd like an interpreter for `Typescript` that uses `ts-node` and works with filetype `.ts`

**Support Level to achieve**
It would be awesome if REPL could be implemented

**Additional context**
I created 2 file 

**test2.ts:**
```
export const substract = (a: number, b: number): void => {
    console.log(a - b);
}
```
**test.ts**
```
import { substract } from "./test2";
substract(4, 2);
```
I run `ts-node test.ts` on terminal
and it gave output `2`

But When I highlight all buffer in `test.ts` then do ` :'<,'>SnipRun` I got following error:
```
RuntimeError: /opt/homebrew/lib/node_modules/ts-node/src/index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
../../Library/Caches/sniprun/typescript_original/main.ts(1,27): error TS2307: Cannot find module './test2' or its corresponding type declarations.
    at createTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  diagnosticText: "../../Library/Caches/sniprun/typescript_original/main.ts(1,27): error TS2307: Cannot find module './test2' or its corresponding type declarations.\n",
  diagnosticCodes: [ 2307 ]
}
```
It seems, `ts-node` support multiple file, is it possible to make it happen? Thanks in advance 🙂

**Comment by Tus1688** [comment]
#114

**Comment by michaelb** [comment]
Are you sure this is what you want?

This is not quite alike what was discussed in the previous issue, and would be impractical to use in the real world unless LSP support is up, which is one order of magnitude harder than enabling repl support for typescript

Reminder: REPL support mean that you'll be able to sniprun lines / blocs separately and the subsequent runs will have a 'memory' of the variables, functions etc... defined in the previous runs

**Comment by Tus1688** [comment]
> IIRC typescript is only supported up to bloc level: you can't send to sniprun different lines of code and expect it to have a 'memory' of variables previously sent.

My apologizes, I thought "memory" was beyond what you said. To clarified, running sniprun from lines / blocs that has memory of the variables/function defined in the previous runs is enough for me.
